### ISSUE TITLE
provisioner execs a new shell repeatedly without virtualenv

### ISSUE THREAD

**Issue by medberry** [network-automation/linklight#44]
Provisioner is erroring with an unknown parameter. botocore version I am running is 1.10.

(mypips) [medberry@thestrel provisioner]$ python 
Python 2.7.14 (default, Mar 14 2018, 13:36:31) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import botocore
>>> print botocore.__version__
1.10.42
>>> 

ah, but it looks like the provisioner is NOT always running inside of my virtualenv and is dropping down to the shell (which only has 1.6.0 not 1.10.42). Sheesh, why is it calling straight to the shell?

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_fbiOxX/ansible_module_ec2_vpc_subnet.py", line 266, in handle_waiter
    **waiter_params(module, params, start_time)
  File "/usr/lib/python2.7/site-packages/botocore/waiter.py", line 295, in wait
    response = self._operation_method(**kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/waiter.py", line 84, in __call__
    return self._client_method(**kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 575, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 630, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/lib/python2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Unknown parameter in input: "WaiterConfig", must be one of: Filters, SubnetIds, DryRun

**Comment by IPvSean** [comment]
Did you set what Ansible is using?  You need to set the
ansible_python_interpreter in your ansible.cfg if you are going to be using
venv with Ansible.

**Comment by medberry** [comment]
I'll try that. Thanks.
