### ISSUE TITLE
Put student inventory in proper spot

### ISSUE THREAD

**Issue by LDSanches** [network-automation/linklight#91]
TASK [control_node : Put student inventory in proper spot (NETWORKING MODE)] *****************************************************************************************************************
task path: /home/lsanches/GIT-REDHAT/linklight/provisioner/roles/control_node/tasks/networking.yml:55
<204.236.245.220> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<204.236.245.220> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/home/lsanches/GIT-REDHAT/linklight/provisioner/TESTESA/TESTESA-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/home/lsanches/.ansible/cp/5c5e409aba 204.236.245.220 '/bin/sh -c '"'"'echo ~ec2-user && sleep 0'"'"''
<204.236.245.220> (0, '/home/ec2-user\n', '')
<204.236.245.220> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<204.236.245.220> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/home/lsanches/GIT-REDHAT/linklight/provisioner/TESTESA/TESTESA-private.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/home/lsanches/.ansible/cp/5c5e409aba 204.236.245.220 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1533682547.86-267810028279150 `" && echo ansible-tmp-1533682547.86-267810028279150="` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1533682547.86-267810028279150 `" ) && sleep 0'"'"''
<204.236.245.220> (0, 'ansible-tmp-1533682547.86-267810028279150=/home/ec2-user/.ansible/tmp/ansible-tmp-1533682547.86-267810028279150\n', '')
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/copy.py", line 442, in run
    source = self._find_needle('files', source)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 1057, in _find_needle
    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
  File "/usr/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 322, in path_dwim_relative_stack
    raise AnsibleFileNotFound(file_name=source, paths=[to_text(p) for p in search])
AnsibleFileNotFound: Could not find or access '/home/lsanches/GIT-REDHAT/linklight/provisioner/TESTESA/student1-instances.txt' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

fatal: [TESTESA-student1-ansible]: FAILED! => {
    "changed": false, 
    "msg": "Could not find or access '/home/lsanches/GIT-REDHAT/linklight/provisioner/TESTESA/student1-instances.txt' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
}

PLAY RECAP ***********************************************************************************************************************************************************************************
TESTESA-student1-ansible   : ok=18   changed=13   unreachable=0    failed=1   
TESTESA-student1-host1     : ok=7    changed=5    unreachable=0    failed=0   
localhost                  : ok=61   changed=25   unreachable=0    failed=0

**Comment by LDSanches** [comment]
Done, this point is working fine! Thanks for your help.
